Djob_Master/urls.py
import debug_toolbar
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from apis.views import MyObtainToken

from Djob_Master import settings
from apis.views import FacebookLogin, TwitterLogin
from apis.custom_token import MyTokenObtainPairView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("account/", include("allauth.urls")),
    path("profile/", include("djob_profile.urls")),
    path("jobs/", include("djob_jobs.urls")),
    # path('rts/', include('random_tester.urls')),
    # Ckeditor
    url(r"^ckeditor/", include("ckeditor_uploader.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    
    # APIS
    path("api/v1/", include("apis.urls")),
    path(
        "swagger<str>:format",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "docs/api/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),

    path('auth/', include('dj_rest_auth.urls')),
    path('auth/registration/', include('dj_rest_auth.registration.urls')),
    path('auth/facebook/', FacebookLogin.as_view(), name='fb_login'),
    path('auth/twitter/', TwitterLogin.as_view(), name='twitter_login'),
    path("api/v1/token_auth/", MyObtainToken.as_view()),
    path("api/v1/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/v1/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/v1/custom-token/", MyTokenObtainPairView.as_view()),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apis/urls.py
from rest_framework import routers
from .views import (
    UserViewSet,
    JobViewSet,
    ProfileViewSet,
    EducationViewSet, 
    ExperienceViewSet
)


router = routers.DefaultRouter()
router.register(r'users', UserViewSet, basename='users')
router.register(r'jobs', JobViewSet, basename='jobs')
router.register(r'profiles', ProfileViewSet, basename='profiles')
router.register(r'educations', EducationViewSet, basename='educations')
router.register(r'experiences', ExperienceViewSet, basename='experiences')

urlpatterns = router.urls

djob_profile/urls.py
from django.urls import path
from .views import ProfileDetailView, ProfileUpdateView, EducationFormView, ExperienceFormView

urlpatterns = [
    path('<int:pk>', ProfileDetailView.as_view(), name='profile'),
    path('<int:pk>/edit', ProfileUpdateView.as_view(), name='profile_update'),
    path('<int:pk>/edit_experience', ExperienceFormView.as_view(), name='update_exp'),
    path('<int:pk>/edit_education', EducationFormView.as_view(), name='update_edu'),
]

djob_profile/models.py
from ckeditor.fields import RichTextField
from django.db import models
from Djob_Master import settings

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profiles')
    summary = RichTextField(default="Enter something awesome about yourself.")
    phone = models.CharField(max_length=15, blank=True, help_text='Contact phone number')
    zipcode = models.CharField(max_length=255, default='17055')
    location = models.CharField(max_length=300, null=True, blank=True)


    EMPLOYMENT_TYPES = (
        ("FT", "Full Time"),
        ("PT", "Part-Time"),
        ('IT', "Internship"),
        ('CT', "Contract"),
    )
    current_job = models.CharField(max_length=75, null=True, default="Awesome Job")
    employment_type = models.CharField(
        max_length=2,
        choices=EMPLOYMENT_TYPES,
        default="FT",
    )

    WA = (
        ('UC', "US Citizen"),
        ('CC', "Canadian Citizen"),
        ('GC', "Green Card Holder"),
        ('EA', "Employment Auth Document"),
        ('NV', "Need H1 Visa"),
        ('HV', "have N1 Visa")
    )

    work_authorization = models.CharField(
        max_length=2,
        choices=WA,
        default="UC",
    )
    availability = models.CharField(default="As soon as possible", max_length=150)
    minimum_salary = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    relocate = models.BooleanField(default=False)
    travel = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username.capitalize()} Profile | ID-{self.id}'


class Education(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    institution = models.CharField(default='Default - Harvard', max_length=200, null=True, blank=True)
    degree = models.CharField(default='Default - Engineering', max_length=150, null=True, blank=True)
    grad_date = models.CharField(default='Default - 2021', max_length=150, null=True, blank=True)

    def __str__(self):
        return f'{self.user.username.capitalize()} Education'


class Experience(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    job_title = models.CharField(default='Default - Engineer', max_length=150, null=True, blank=True)
    time_at_job = models.CharField(default='Default - 1 year', max_length=150, null=True, blank=True)
    job_location = models.CharField(default='Default - Los Angeles', max_length=150, null=True, blank=True)
    job_description = models.TextField(default='Default - I am an engineer')

    def __str__(self):
        return f'{self.user.username.capitalize()} Experience'

djob_profile/forms.py
from django.forms.models import ModelForm, modelformset_factory

from .models import Profile, Education, Experience


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['summary', 'location', 'minimum_salary', 'employment_type', 'work_authorization', 'relocate',
                  'travel', 'relocate', 'phone', 'current_job']


class EducationForm(ModelForm):
    class Meta:
        model = Education
        fields = [
            'institution', 'degree', 'grad_date', 'id'
        ]


class ExperienceForm(ModelForm):
    class Meta:
        model = Experience
        fields = [
            'job_title', 'job_description', 'job_location', 'time_at_job', 'id'
        ]


EducationFormSet = modelformset_factory(Education, exclude=(), extra=0, can_delete=True)
ExperienceFormSet = modelformset_factory(Experience, exclude=(), extra=0, can_delete=True)

djob_profile/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, FormView

from users.forms import CustomUserForm
from users.models import User
from .forms import ProfileForm, ExperienceFormSet, EducationFormSet
from .models import Profile, Education, Experience


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'djob_profile/profile.html'
    context_object_name = 'profile'
    fields = ['summary', 'location', 'minimum_salary', 'employment_type', 'work_authorization', 'relocate',
              'travel', 'relocate', 'phone', 'current_job']


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'djob_profile/profile_edit.html'
    model = Profile
    form_classes = ProfileForm

    fields = ['summary', 'location', 'minimum_salary', 'employment_type', 'work_authorization', 'relocate',
              'travel', 'relocate', 'phone', 'current_job']

    def get_second_form(self):
        # logic to construct second form goes here
        # if self.request.method == 'POST' you need to pass self.request.POST
        # to the form. Add whatever you need to create the form
        context = {}
        if self.request.method == 'POST':
            obj = User.objects.get(pk=self.request.user.pk)
            # edu = Education.objects.get(user_id=self.request.user.id)

            form = CustomUserForm(initial={
                'first_name': obj.first_name,
                'last_name': obj.last_name,
                'email': obj.email})

            context['user'] = form
            # context['edu'] = edu

            return context
        else:
            return CustomUserForm()

    def form_valid(self, form):

        """
        Args:
            form:
        """
        if self.request.method == 'POST':

            self.object.maker = Profile.objects.get(pk=self.request.user.pk)

            # Grabs the data from the form with the POST method
            fn = self.request.POST.get('first_name')
            ln = self.request.POST.get('last_name')
            em = self.request.POST.get('email')

            # Loads the second form and updates the database with the form data
            obj = User.objects.get(pk=self.request.user.pk)
            obj.email = em
            obj.first_name = fn
            obj.last_name = ln
            obj.save()

            form.save()

            return super(ProfileUpdateView, self).form_valid(form)
        else:
            return redirect(self.get_success_url())

    def form_invalid(self, **kwargs):
        """
        Args:
            **kwargs:
        """
        return self.render_to_response(self.get_context_data(**kwargs))

    def get_success_url(self):
        return reverse_lazy('profile', args=[self.object.id])

    def get_context_data(self, **kwargs):
        """
        Args:
            **kwargs:
        """
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)

        # Gets the data from the current user
        user_obj = User.objects.get(pk=self.request.user.pk)

        # applies initial data to the form
        # This is necessary so the form doesn't show up blank.
        user_form = CustomUserForm(initial={
            'first_name': user_obj.first_name,
            'last_name': user_obj.last_name,
            'email': user_obj.email
        })

        context['user_form'] = user_form
        return context


class EducationFormView(LoginRequiredMixin, FormView):
    template_name = 'djob_profile/education_update.html'
    form_class = EducationFormSet

    def get_success_url(self):
        return reverse_lazy('profile', args=[self.request.user.id])

    def get_context_data(self, **kwargs):
        """
        Args:
            **kwargs:
        """
        context = super(EducationFormView, self).get_context_data(**kwargs)

        context['profile'] = Profile.objects.get(id=self.request.user.pk)
        context['experience'] = ExperienceFormSet(queryset=Experience.objects.filter(user=self.request.user.id))

        if self.request.POST:
            context['edu_formset'] = EducationFormSet(self.request.POST)
        else:
            context['edu_formset'] = EducationFormSet(queryset=Education.objects.filter(user=self.request.user.id))
        return context

    def form_valid(self, form):

        """
        Args:
            form:
        """
        context = self.get_context_data()
        formset = context['edu_formset']
        print(form.deleted_forms)

        if formset.is_valid():
            formset.save()
            messages.success(self.request, 'Education successfully updated.')
        return super(EducationFormView, self).form_valid(form)


class ExperienceFormView(LoginRequiredMixin, FormView):
    template_name = 'djob_profile/experience_update.html'
    form_class = ExperienceFormSet
    model = Profile

    def get_success_url(self):
        return reverse_lazy('profile', args=[self.request.user.id])

    def get_context_data(self, **kwargs):
        """
        Args:
            **kwargs:
        """
        context = super(ExperienceFormView, self).get_context_data(**kwargs)
        context['profile'] = Profile.objects.get(id=self.request.user.get_profile())


        if self.request.POST:
            context['exp_formset'] = ExperienceFormSet(self.request.POST)
        else:
            context['exp_formset'] = ExperienceFormSet()
        return context

    def form_valid(self, form):
        """
        Args:
            form:
        """
        context = self.get_context_data()
        formset = context['exp_formset']

        if formset.is_valid():
            formset.save()
            messages.success(self.request, 'Experience successfully updated.')
        return super(ExperienceFormView, self).form_valid(form)

djob_profile/templates/djob_profile/profile_components/display_edu.html
<section class='mt-10'>

    <div class="max-w-4xl px-8 py-4 mx-auto bg-white rounded shadow-lg dark:bg-gray-800">

        <div class="lg:w-full">

            <div class="flex flex-col sm:flex mb-4 items-center">
                <h2 class="flex-none text-3xl font-bold text-gray-800 dark:text-gray-100">Education</h2>
                <div>

                    <button class="hidden flex-no-shrink p-2 ml-4 mr-2 text-center mx-auto">
                        <svg class="h-10 w-10"
                             id="color" enable-background="new 0 0 24 24" height="512" viewBox="0 0 24 24" width="512"
                             xmlns="http://www.w3.org/2000/svg">
                            <path d="m15.854 23.146c-1.313-1.313-1.353-2.586-1.354-2.649-.002-.275-.225-.497-.5-.497h-4.02c-.276 0-.5.227-.5.503 0 .054-.018 1.328-1.333 2.644-.143.143-.186.358-.108.545.076.186.259.308.461.308h7c.202 0 .385-.122.462-.309s.034-.401-.108-.545z"
                                  fill="#90a4ae"/>
                            <path d="m14.25 4c-.414 0-.75-.336-.75-.75v-1.5c0-.138-.112-.25-.25-.25h-2.5c-.138 0-.25.112-.25.25v1.5c0 .414-.336.75-.75.75s-.75-.336-.75-.75v-1.5c0-.965.785-1.75 1.75-1.75h2.5c.965 0 1.75.785 1.75 1.75v1.5c0 .414-.336.75-.75.75z"
                                  fill="#64b5f6"/>
                            <path d="m16.25 10.5h-8.5c-.965 0-1.75-.785-1.75-1.75v-4.5c0-.965.785-1.75 1.75-1.75h8.5c.965 0 1.75.785 1.75 1.75v4.5c0 .965-.785 1.75-1.75 1.75z"
                                  fill="#2196f3"/>
                            <path d="m18 7h-12v-1.5h12z" fill="#64b5f6"/>
                            <path d="m12 8c-.414 0-.75-.336-.75-.75v-2c0-.414.336-.75.75-.75s.75.336.75.75v2c0 .414-.336.75-.75.75z"
                                  fill="#64b5f6"/>
                            <path d="m24 5.75v13.5c0 .96-.79 1.75-1.75 1.75h-20.5c-.96 0-1.75-.79-1.75-1.75v-13.5c0-.96.79-1.75 1.75-1.75h2.78l-.03.25v1.75h-2.5v11h20v-11h-2.5v-1.75l-.03-.25h2.78c.96 0 1.75.79 1.75 1.75z"
                                  fill="#607d8b"/>
                            <path d="m22 6v11h-20v-11h2.5v2.75c0 1.79 1.46 3.25 3.25 3.25h8.5c1.79 0 3.25-1.46 3.25-3.25v-2.75z"
                                  fill="#f5f5f5"/>
                            <path d="m12 21h-2.591c-.118.501-.431 1.315-1.262 2.146-.143.143-.186.358-.108.545.076.187.259.309.461.309h3.5z"
                                  fill="#7d8f97"/>
                            <path d="m12 0h-1.25c-.965 0-1.75.785-1.75 1.75v.75h1.5v-.75c0-.138.112-.25.25-.25h1.25z"
                                  fill="#579ed6"/>
                            <path d="m12 2.5h-1.5-1.5-1.25c-.965 0-1.75.785-1.75 1.75v4.5c0 .965.785 1.75 1.75 1.75h4.25v-2.5c-.414 0-.75-.336-.75-.75v-.25h-5.25v-1.5h5.25v-.25c0-.414.336-.75.75-.75z"
                                  fill="#1d83d4"/>
                            <path d="m11.25 5.5h-5.25v1.5h5.25z" fill="#579ed6"/>
                            <path d="m12 4.5c-.414 0-.75.336-.75.75v.25 1.5.25c0 .414.336.75.75.75z" fill="#579ed6"/>
                            <path d="m4.53 4h-2.78c-.96 0-1.75.79-1.75 1.75v13.5c0 .96.79 1.75 1.75 1.75h7.659 2.591v-4h-10v-11h2.5v-1.75z"
                                  fill="#546d79"/>
                            <path d="m4.5 6h-2.5v11h10v-5h-4.25c-1.79 0-3.25-1.46-3.25-3.25z" fill="#d5d5d5"/>
                        </svg>
                    </button>
                    <a href="{% url 'update_edu' request.user.get_profile %}#EDU" class="flex-no-shrink p-2 ml-4 mr-2 text-center mx-auto">
                        <svg class="w-10 h-10" id="color" enable-background="new 0 0 24 24" height="512" viewBox="0 0 24 24" width="512"
                             xmlns="http://www.w3.org/2000/svg">
                            <path d="m10.842 19.854c.079-.453.295-.868.622-1.197l5.536-5.536v-10.371c0-1.517-1.233-2.75-2.75-2.75h-11.5c-1.517 0-2.75 1.233-2.75 2.75v15.5c0 1.517 1.233 2.75 2.75 2.75h7.89z"
                                  fill="#eceff1"></path>
                            <g fill="#90a4ae">
                                <circle cx="8.5" cy="5" r="2"></circle>
                                <path d="m11.75 12h-6.5c-.414 0-.75-.336-.75-.75v-.5c0-1.517 1.233-2.75 2.75-2.75h2.5c1.517 0 2.75 1.233 2.75 2.75v.5c0 .414-.336.75-.75.75z"></path>
                                <path d="m12 15h-7c-.553 0-1-.448-1-1s.447-1 1-1h7c.553 0 1 .448 1 1s-.447 1-1 1z"></path>
                                <path d="m11 18h-6c-.553 0-1-.448-1-1s.447-1 1-1h6c.553 0 1 .448 1 1s-.447 1-1 1z"></path>
                            </g>
                            <path d="m23.487 13.351-1.237-1.237c-.49-.49-1.386-.737-2.298.177l-7.425 7.424c-.108.109-.182.249-.208.4l-.53 3.005c-.09.504.346.958.868.869l3.005-.53c.152-.027.292-.1.4-.209l7.425-7.425c.683-.682.683-1.792 0-2.474z"
                                  fill="#2196f3"></path>
                            <path d="m22.911 12.775-11.032 10.852c.129.221.369.373.647.373.043 0 .087-.004.131-.011l3.005-.53c.152-.027.292-.1.4-.209l7.425-7.425c.683-.682.683-1.792 0-2.475z"
                                  fill="#1d83d4"></path>
                            <path d="m8.5 0h-5.75c-1.517 0-2.75 1.233-2.75 2.75v15.5c0 1.517 1.233 2.75 2.75 2.75h5.75v-3h-3.5c-.552 0-1-.448-1-1s.448-1 1-1h3.5v-1h-3.5c-.552 0-1-.448-1-1s.448-1 1-1h3.5v-1h-3.25c-.414 0-.75-.336-.75-.75v-.5c0-1.517 1.233-2.75 2.75-2.75h1.25v-1c-1.103 0-2-.897-2-2s.897-2 2-2z"
                                  fill="#cdd0d2"></path>
                            <path d="m8.5 3c-1.103 0-2 .897-2 2s.897 2 2 2z" fill="#7d8f97"></path>
                            <path d="m8.5 8h-1.25c-1.517 0-2.75 1.233-2.75 2.75v.5c0 .414.336.75.75.75h3.25z" fill="#7d8f97"></path>
                            <path d="m8.5 13h-3.5c-.552 0-1 .448-1 1s.448 1 1 1h3.5z" fill="#7d8f97"></path>
                            <path d="m8.5 16h-3.5c-.552 0-1 .448-1 1s.448 1 1 1h3.5z" fill="#7d8f97"></path>
                        </svg>
                    </a>

                </div>

                <br class="sm:hidden">

            </div>
            <div class="grid grid-cols-2 gap-4">
                 <p class="w-full font-medium text-grey-darkest flex items-center justify-left">Degree Obtained</p>
                <button class="ml-auto flex font-medium items-center justify-center"> Institution - Date</button>
            </div>
        <hr class="mt-4">
            <div class="grid grid-rows-1 gap-4">
                {% for edu in profile.user.education_set.all %}
                <div class="grid grid-cols-2 gap-4 mt-4">
                    <p class="w-full font-medium text-grey-darkest flex items-center justify-left">{{ edu.degree }}</p>
                    <button class="ml-auto flex font-medium items-center justify-center">{{ edu.institution }}
                        - {{ edu.grad_date }}</button>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
</section>